#!/command/with-contenv bash

source /assets/functions/00-container
set -a
source /assets/defaults/10-traefik
source /assets/defaults/20-traefik-cert-dumper
set +a
source /assets/functions/10-traefik

PROCESS_NAME="traefik"

cat <<EOF

******************************************************************************************
*                                                                                        *
*                    END OF LIFE NOTICE AUGUST 18, 2025                                  *
*                               tiredofit/traefik                                        *
*                                                                                        *
* This image is no longer maintained as of and will not receive updates.                 *
*                                                                                        *
* A successor image is available at:                                                     *
*                                                                                        *
* Repository | Documentation:                                                            *
*   - https://github.com/nfrastack/container-traefik                                     *
*                                                                                        *
* Image Registries:                                                                      *
*   - https://hub.docker.com/r/nfrastack/traefik                                         *
*   - https://github.com/nfrastack/container-traefik/pkgs/container/container-traefik    *
*                                                                                        *
* Please visit https://nfrastack.com for more information.                               *
*                                                                                        *
******************************************************************************************

EOF

sleep 15

bootstrap_filesystem
generate_configuration
configure_zabbix

liftoff
