#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service
SERVICE_NAME="traefik-cert-reload"


if [ -n "${TLS_CERT_PATH}" ] || env | grep -q '^TLS_[0-9][0-9]_CERT_FILE='; then
    tls_enabled=true
fi

if var_true "${RELOAD_ON_CERT_CHANGE}" && [ "${tls_enabled}" = "true" ]; then
	print_notice "Enabling Auto Reload of Traefik when certificate files change"
else
	service_stop 21-traefik-cert-reload
fi

liftoff