#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
set -a
source /container/defaults/10-traefik
source /container/defaults/20-traefik-cert-exporter
set +a
source /container/functions/10-traefik

SERVICE_NAME="traefik"

for snippet in "${CONFIG_CUSTOM_PATH%/}"/*; do
    [ -e "${snippet}" ] || continue
    if [ -L "${snippet}" ]; then
        target=$(readlink "$snippet")
        case "${target}" in
            /container/data/traefik/*)
                rm -f "${snippet}"
            ;;
        esac
    fi
done

liftoff
